### PR TITLE
Missing default alarms

### PR DESCRIPTION
**Pull request by fosJoddie**
## Description
This adds two missing default alarms for Facebook and Pushbullet

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Wiki Update
No updates needed 
## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kvangent** [comment]
All PRs should probably be made to the dev branch. That branch contains significant improvements over the master branch and it seems pointless to continue to diverge them farther.

**Comment by fosJoddie** [comment]
Gonna rebase this to dev so dev can be made info master sooner and can move to the same model rocketmap uses with only one current branxh.

**Comment by kvangent** [comment]
As far as I can tell, this change looks redundant? Both alarm types already seem to an egg section from what I can tell. Was their an issue that inspired this change?

**Comment by fosJoddie** [comment]
@kvangent  you are correct, I was somehow comparing my local commits to an older master when making this, They were missing at a time, but quickly added by you I believe

**Pull request closed without merging**
