### PR TITLE
3rd gen

### PR DESCRIPTION
**Pull request by AEtHeLsYn**
## Description
Add support of 3rd gen Pokemon

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (would cause existing functionality to change)

## Motivation and Context
Add support of upcoming 3rd gen 

## How Has This Been Tested?
Local instance

## Wiki Update
- [ ] This change requires an update to the Wiki.
- [x] This change does not require an update to the Wiki.

## Checklist
- [x] This change follows the code style of this project.
- [x] This change only changes what is necessary to the feature.

### CODE REVIEW

**Comment by kvangent** [comment]
Why have all the stickers changed and not just new ones added in?

**Comment by AEtHeLsYn** [comment]
Stickers for gen 1 and 2 are almost the same, just reworked with some Photoshop. Stickers for 3rd gen come from the same place, i'll update the PR with a couple of them.

**Comment by elincognito** [comment]
Doesn't this miss pokemon `Kyroge` accordingly to https://bulbapedia.bulbagarden.net/wiki/Kyogre_(Pok%C3%A9mon)

**Comment by AEtHeLsYn** [comment]
i tested all stickers, Kyroge is 384

**Comment by kvangent** [comment]
I pulled f7da1187030ac60456bb9df6e9371edea829be9d which covers this feature. 

If you think your stickers are superior to the older ones, please feel free to submit a new PR with reasons explaining why (and perhaps some examples) and we can reevaluate then.

**Pull request closed without merging**
