### PR TITLE
Pickle cache

### PR DESCRIPTION
**Pull request by fosJoddie**
## Description
Introduces two new options for PA:

`use-adr-file-cache`: Cache google address lookups in a file cache. Since most maps have very static spawn point and gym position data, the need to look up addresses repeatedly is limited and it makes sense to save requests by caching the information.
`use-gym-file-cache`: Cache gym details in a file cache so that a freshly started PA do not have to rely on RM for getting gym information.

- Cached information is automatically saved every 10 seconds, or if PokeAlarm is exited with Ctrl+C or any other graceful method.

address DTS has been changed a tiny bit. It now will return an empty value if street name or street number is unknown. This allows for streets that have no numbers (like squares) to show up correctly.
In addition there's a new DTS called `<address_eu>` that will write out "Alphabet Street 123" as addresses is usually written in Europe/Most of the world(?)

Lastly this also include a minor change where the gym processing would check if it was inside geofence twice.

I realize this PR is not compatible with current dev branch, but I made this one already back before dev had caching so I found it easier to finish this one instead of trying to merge what I did with what dev has. 

## How Has This Been Tested?
Tested locally for an extensive time with no issues. 
Been running for 1 month with 10 managers with alarms for pokemon and raids. tested both with imported cache files and fresh ones.
Not tested anything of gyms, but should be unchanged

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Wiki Update
Need to update the config section on how to enable the cachings and also with information about where to go to clear it if wanted.

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Goldclownfish** [comment]
Caching is against googles tos.

**Comment by pogo-excalibur** [comment]
From my comment on #328:

Do be mindful of this: https://developers.google.com/maps/terms#section_10_5

(Specifically the 'No caching or storage' section).

If you read the document, caching to reduce the number of requests sent should be fine so long as the cache is only persisted for up to 30 days.

(I believe this restriction may be relaxed if you are using a premium API key).

**Comment by Goldclownfish** [comment]
No caching or storage. You will not pre-fetch, cache, index, or store any Content to be used outside the Service, except that you may store limited amounts of Content solely for the purpose of improving the performance of your Maps API Implementation due to network latency (and not for the purpose of preventing Google from accurately tracking usage), and only if such storage:
is temporary (and in no event more than 30 calendar days);
is secure;
does not manipulate or aggregate any part of the Content or Service; and
does not modify attribution in any way.     

Don’t think u can get around this because caching this has nothing to do with latency issues

**Comment by fosJoddie** [comment]
Meanwhile people use multiple free google keys, with no concern. 

I’m fine if it isn’t allowed, but: 

`You will not pre-fetch, cache, index, or store any Content to be used outside the Service` Says: used OUTSIDE the service. I am not concinced limited caching falls outside their terms. 

Anyhow I am going to rebase this against the dev branch when I can, which btw already caches geocode results in memory, fyi.

**Comment by kvangent** [comment]
Just to weigh in here, my interpretation is that caching in memory is fine because it is temporary to a degree (it seems unlikely PA will be running for over 30 consecutive days) but writing for a file may break that use case.

Also, the reason we haven't added in rotating keys is because I want to be wary of abuse. I added in one per manager because I felt the separation of those managers is close enough to 'different projects' and not different than launching multiple instances of PA. 

I think caching the gym info to file is a great idea (one that I've tried to implement in the gym_cache branch) and would love to incorporate it into PA.

**Pull request closed without merging**
