### PR TITLE
Update URLs for RocketMap repo

### PR DESCRIPTION
**Pull request by wickles**
## Description

Updated old image URLs from `kvangent` repo to `RocketMap` repo

## How Has This Been Tested?

Checked that the new URLs are accessible. They are.

## Screenshots (if appropriate):

N/A

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Wiki Update

Wiki also has URLs that should be updated

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kvangent** [comment]
This should really be submitted to the dev branch if anything.

**Comment by wickles** [comment]
@kvangent what's the difference, or what are the intended purposes for the two branches? I notice the dev branch is ahead a few and behind a few commits.

**Comment by kvangent** [comment]
The intended purpose for the dev branch is to accumulate changes and release them in patches to the main branch. The reason for this is alot of times commits change or break older configurations for PA - the dev branch lets the more tech savy users try out the changes. When they get merged into main I release patch notes to help people catch up there configurations.

**Comment by wickles** [comment]
I changed base but noticed that it added in similar branding updates already made to master. Not sure how you would like to handle that.

**Comment by kvangent** [comment]
You need to rebase instead of merge. They way you've done it now changes some things that should be changed.

It might be easiest to just take the dev branch from start and do the find and replace from there.

**Comment by wickles** [comment]
Fixed, please review

**Comment by MARTINI1** [comment]
I do not know but this I see something strange since there are things fixes in the master branch that are here to be fixed again

#422 #423 & #424 

I just think that the only thing that is uncorrected are the url in discord, facebook, slack and manager

**Comment by wickles** [comment]
🤦‍♂️

**Comment by MARTINI1** [comment]
haha, now that the PR is fine

what do not know is when you will merge the dev branch into the master

**Comment by kvangent** [comment]
I think you are better off just changing all instances to the correct url, regardless if they are already done in master. It will make it much easier to just merge the entire branch in.

**Comment by wickles** [comment]
🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️

**Pull request merged**
